name: medical_history
description: Medical history tracker.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 2.0.0+4

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_hooks: ^0.14.1
  hooks_riverpod: ^0.12.1
  shared_preferences: ^0.5.12+2
  get_it: ^5.0.1
  permission_handler: ^5.0.1+1
  package_info: ^0.4.3
  flutter_spinkit: ^4.1.2+1
  flutter_page_transition: ^0.1.6
  sized_context: ^0.2.1+1
  hive: ^1.4.4+1
  hive_flutter: ^0.3.1
  xml: ^4.5.1
  html: ^0.14.0+4
  http: ^0.12.2
  mask_text_input_formatter: ^1.1.0
  flutter_secure_storage: ^3.3.5
  encrypt: ^4.1.0
  rflutter_alert: ^1.1.0
  dropdown_suggestions_form_field: ^1.0.3
  network_to_file_image: ^2.3.6
  drop_cap_text: ^1.0.7
  expandable: ^4.1.4

  cupertino_icons: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  hive_generator: ^0.8.1
  build_runner: ^1.10.3

flutter:
  uses-material-design: true

  assets:
    - assets/meds.png
    - assets/drug.jpg
    - assets/drug-2.png
    - assets/doctor.png
    - assets/doctor-1.png
    - assets/medical-history.png
    - assets/categories.json
