name: medical_history
description: Medical history tracker.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_hooks: ^0.14.0
  hooks_riverpod: ^0.11.0
  shared_preferences: ^0.5.12
  get_it: ^5.0.1
  permission_handler: ^5.0.1+1
  package_info: ^0.4.3
  flutter_spinkit: ^4.1.2+1
  flutter_page_transition: ^0.1.6
  sized_context: ^0.2.1+1
  hive: ^1.4.4
  hive_flutter: ^0.3.1
  xml: ^4.5.1
  http: ^0.12.2
  mask_text_input_formatter: ^1.1.0
  flutter_secure_storage: ^3.3.4
  encrypt: ^4.0.3
  rflutter_alert: ^1.1.0

  cupertino_icons: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  hive_generator: ^0.7.2+1
  build_runner: 1.10.1

flutter:
  uses-material-design: true

  assets:
    - assets/meds.png
    - assets/drug.jpg
    - assets/doctor.png
